### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Iomega0318** [antonyho/runuo-donation-store#1]
Are there any plans to update this?

I would be willing to donate towards such an endeavor.

**Comment by antonyho** [comment]
I'm sorry! I was not active on this script pack for a long period. Didn't check this repository regularly. Not sure if you still need help or not. I'm not asking for any tip, and I don't expect it any more. As I cannot commit myself on it to make it better. I just don't deserve any more tip from it.
If I would invest my time on this script pack, I would not write it in PHP. But rather create a standalone containerised web module in Go. And support selections of database system for administrator to choose from.

I'm sorry this ticket is more than one year old. There is no point to keep it open. If you have any trouble on applying it, please create a new issue ticket and elaborate your issue with error message or log.
